name       : jhead
version    : 3.06.0.1
release    : 1
source     :
    - https://github.com/Matthias-Wandel/jhead/archive/refs/tags/3.06.0.1.tar.gz : 5c5258c3d7a840bf831e22174e4a24cb1de3baf442f7cb73d5ab31b4ae0b0058
license    : Public Domain
component  : multimedia.graphics
summary    : Command line program to display and manipulate Exif headers
description: |
    JHEAD is a simple command line tool for displaying and some manipulation of EXIF header data embedded in jpeg images from digital cameras.
build      : |
    %make
install    : |
    %make_install
