name       : jhead
version    : '3.08'
release    : 2
source     :
    - https://github.com/Matthias-Wandel/jhead/archive/refs/tags/3.08.tar.gz : 999a81b489c7b2a7264118f194359ecf4c1b714996a2790ff6d5d2f3940f1e9f
homepage   : https://github.com/Matthias-Wandel/jhead
license    : Public Domain
component  : multimedia.graphics
summary    : Command line program to display and manipulate Exif headers
description: |
    JHEAD is a simple command line tool for displaying and some manipulation of EXIF header data embedded in jpeg images from digital cameras.
setup      : |
    %patch -p1 < $pkgfiles/makefile.patch
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/doc
